### ISSUE TITLE
Add Rhino Object-error

### ISSUE THREAD

**Issue by SJJ3D** [ALanMAttano/Blender_4_Rhino#2]
I did all the steps as described, I only changed the path 2 times in the .py file to match the correct folder path for the .obj

The export works in Rhino 7, however, when I'm in Blender 4.7 going to add->mesh->import rhino object throws me an error:

Python: Traceback (most recent call last):
  File "C:\Users\(windows name)\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\A Blender 4 Rhino.py", line 31, in execute
    bpy.ops.import_scene.obj(filepath=full_path_to_file, axis_forward='-Z', axis_up='Y', filter_glob="*.obj;*.mtl")
  File "D:\Program Files\Blender Foundation\Blender\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.import_scene.obj" error, could not be found

Any solutions to that?
The output folder has an MTL file and an OBJ.

**Comment by SJJ3D** [comment]
FIXED
Okay it looks like i've answered my own question. Turns out bpy.ops.import_scene.obj was removed at bpy>=4 which is the latest blender-api for python, hence the error. In bpy>4 you have to use bpy.ops.wm.obj_import(filepath='')

Below is the fixed .py

bl_info = {
    "name": "New Rhino Object - A Blender 4 Rhino",
    "author": "Alan Mattano, Soaring Stars lab",
    #"co-authors": "Adri. Negro, ",
    "version": (0, 7),
    "blender": (4, 0, 0),  # Updated for Blender 4+
    "location": "View3D > Add > Mesh > New Rhino Object",
    "description": "Adds a new Mesh Object - A Blender 4 Rhino",
    "warning": "",
    "wiki_url": "https://github.com/ALanMAttano/Blender_4_Rhino",
    "category": "Add Mesh",
}

import bpy
from bpy.types import Operator
from bpy.props import FloatVectorProperty
from bpy_extras.object_utils import AddObjectHelper, object_data_add
from mathutils import Vector

class OBJECT_OT_add_object(Operator, AddObjectHelper):
    """Import a Rhino Mesh Object"""
    bl_idname = "mesh.add_object"
    bl_label = "Add Mesh Object"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):        
        full_path_to_file = "X:\\(your parth)\\Rhino-Blender-mesh.obj"
        bpy.ops.wm.obj_import(filepath=full_path_to_file)  # Updated for Blender 4+
        return {'FINISHED'}

def add_object_button(self, context):
    self.layout.operator(
        OBJECT_OT_add_object.bl_idname,
        text="Add Rhino Object",
        icon='PLUGIN')

# This allows you to right-click on a button and link to documentation
def add_object_manual_map():
    url_manual_prefix = "https://discourse.mcneel.com/t/"
    url_manual_mapping = (
        ("bpy.ops.mesh.add_object", "rhino-to-blender-mesh-bridge-import-and-export/94448"),
    )
    return url_manual_prefix, url_manual_mapping

#----------------------------------------------------------------------------

class OBJECT_OT_add_objectexport(Operator, AddObjectHelper):
    """Export a Rhino Mesh Object"""
    bl_idname = "mesh.add_objectexport"
    bl_label = "Save Mesh Object"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):        
        print("Exporting...")
        full_path_to_file = "X:\\(your path)\\Rhino-Blender-mesh.obj"
        bpy.ops.export_scene.obj(filepath=full_path_to_file, use_selection=True)
        return {'FINISHED'}

def add_objectexport_button(self, context):
    self.layout.operator(
        OBJECT_OT_add_objectexport.bl_idname,
        text="Save Rhino Object",
        icon='PLUGIN')

# Registration

def register():
    bpy.utils.register_class(OBJECT_OT_add_object)
    bpy.utils.register_manual_map(add_object_manual_map)
    bpy.types.VIEW3D_MT_mesh_add.append(add_object_button)
    
    bpy.utils.register_class(OBJECT_OT_add_objectexport)
    bpy.types.VIEW3D_MT_mesh_add.append(add_objectexport_button)

def unregister():
    bpy.utils.unregister_class(OBJECT_OT_add_object)
    bpy.utils.unregister_manual_map(add_object_manual_map)
    bpy.types.VIEW3D_MT_mesh_add.remove(add_object_button)
    
    bpy.utils.unregister_class(OBJECT_OT_add_objectexport)
    bpy.types.VIEW3D_MT_mesh_add.remove(add_objectexport_button)

if __name__ == "__main__":
    register()
